### ISSUE TITLE
"No loaded DialogHost instances." exception on SingleActionDialog.ShowAsync()

### ISSUE THREAD

**Issue by Kruno313** [Bip901/AvaloniaDialogs#2]
I get the above exception calling ShowAsync().
I am missing something for sure, because the Demo works, but I can't figure it out what.

**Comment by Bip901** [comment]
Hi, you need to make sure that the following are true:

* At the time of the `ShowAsync` call, you had a `<ReactiveDialogHost>` somewhere in the open Window
* The dialog host was loaded completely before the call. If you want to show a dialog immediately when the window opens, do it in an event like `Loaded` rather than the constructor. See also: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/436

**Comment by Kruno313** [comment]
Thanks, the missing <ReactiveDialogHost> was the problem, hence I was sure I put that in once when trying to get it work.

Now I have second issue: the dialog shows, but transparent and the background view is still active and reacting, while the SingleActionDialog is transparent and his buttons also reacts to the click. The dialog is not modal.
My code in the active View (one of three that can be shown):
```
async Task<string> ShowErrorDialog(string text) { 
    SingleActionDialog dialog = new() {
        Message = text,
        ButtonText = "OK"
     };
     await dialog.ShowAsync();
     return "OK";
}
```
Result:
![ShowDialog](https://github.com/user-attachments/assets/03191517-0a92-49aa-8bbe-d0a656f0966f)

Setting Background to Brushes.Gray makes it visible (intransparent), but still not modal.

**Comment by Bip901** [comment]
Hi, I'm glad you solved the first issue.

As for the second issue, if you believe it may be a bug, please attach a minimal reproducible example (e.g. `App.axaml` and Window axaml files) in a new issue so I can investigate.

**Comment by Kruno313** [comment]
I'm not sure if it is a bug or it just has to do with the ViewLocator pattern I used. The original app I streamed down to this demo project has three views switching on connection and so on.
This project contains only the first view for simplicity. Maybe You can check it for problems.
Thanks in forward.
[MinimalDialogPrj.zip](https://github.com/user-attachments/files/16889628/MinimalDialogPrj.zip)

**Comment by Bip901** [comment]
Looks the upstream `DialogHost.Avalonia` library had a bug with Avalonia 11.1 compatibility. (See https://github.com/AvaloniaUtils/DialogHost.Avalonia/issues/48)
Fortunately, it was fixed - so I've released a new version with bumped dependency versions.

Please try updating `AvaloniaDialogs` to version 3.6.0 and see if if solves your problem 😄

**Comment by Kruno313** [comment]
Thanks, the MinimalDialog.prj works well now!
